---
- name: Deploy web app docker container
  tags: deploy
  block:
    - name: Remove container
      include_tasks: wipe_web_app.yml
    - name: Pull image
      include_tasks: pull_image.yml
    - name: Run container
      include_tasks: run_container.yml
...