---
- name: Stop and Remove Docker container
  tags: wipe
  when: web_app_full_wipe
  block:
    - name: Remove Docker container
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        state: absent
    - name: Remove Docker image
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        state: absent
...